title: Generative AI Portfolio — Shirish Utage
description: A curated portfolio highlighting my hands-on experience through internships, machine learning projects, and practical applications in Generative AI.
